// Layer 1 — Prompt. The technique blocks for a single model call.
// The health score and the hallucination badge in AceStudio.jsx look these
// up by id (role, task, constraints, grounding, uncertainty, format).
export const PROMPT_BLOCKS = [
  {
    id: "role",
    emoji: "🎭",
    label: "Role",
    color: "#7C3AED",
    glow: "#7C3AED44",
    text: "You are an expert [DOMAIN] with [X] years of experience in [SPECIALTY]. Your approach is [STYLE].",
    why: "🎭 Persona Priming\n• Activates domain-specific knowledge in the model\n• Improves accuracy and tone consistency\n• Sets the voice for the entire response",
  },
  {
    id: "context",
    emoji: "🗂️",
    label: "Context",
    color: "#0EA5E9",
    glow: "#0EA5E944",
    text: "Context: [BACKGROUND]. The user is working on [PROJECT]. Key constraints: [CONSTRAINTS].",
    why: "🗂️ Contextual Grounding\n• Anchors the model to your specific situation\n• Reduces generic, one-size-fits-all answers\n• Prevents wrong assumptions about your problem",
  },
  {
    id: "task",
    emoji: "🎯",
    label: "Task",
    color: "#10B981",
    glow: "#10B98144",
    text: "Your task is to [SPECIFIC_ACTION]. Focus on [SCOPE]. Do NOT [EXCLUSIONS].",
    why: "🎯 Task Clarity\n• Defines exact output boundary with action verbs\n• Prevents scope creep and off-topic answers\n• DO NOT exclusions sharpen focus instantly",
  },
  {
    id: "constraints",
    emoji: "🚧",
    label: "Constraints",
    color: "#F59E0B",
    glow: "#F59E0B44",
    text: "Constraints:\n- Only use information provided\n- If unsure, say \"I don't know\"\n- Limit response to [N] words",
    why: "🚧 Guardrails Technique\n• Hard limits reduce hallucination risk\n• Keeps output within verifiable scope\n• Length cap prevents rambling responses",
  },
  {
    id: "cot",
    emoji: "🧠",
    label: "Think Step-by-Step",
    color: "#EC4899",
    glow: "#EC489944",
    text: "Think step by step:\n1. Identify what is being asked\n2. List your assumptions\n3. Reason through the evidence\n4. State your conclusion",
    why: "🧠 Chain-of-Thought (CoT)\n• Forces explicit reasoning before the answer\n• Dramatically improves accuracy on hard tasks\n• Exposes flawed logic before it reaches output",
  },
  {
    id: "format",
    emoji: "📐",
    label: "Output Format",
    color: "#8B5CF6",
    glow: "#8B5CF644",
    text: "Respond using this format:\n[FORMAT_TYPE]\nStructure: [SECTIONS]\nMax length: [N] words",
    why: "📐 Output Schema Control\n• Shifts effort from formatting to content\n• Produces consistent, parseable responses\n• Makes output directly usable without editing",
  },
  {
    id: "examples",
    emoji: "💡",
    label: "Few-Shot Examples",
    color: "#14B8A6",
    glow: "#14B8A644",
    text: "Examples:\n\nInput: [EXAMPLE_INPUT_1]\nOutput: [EXAMPLE_OUTPUT_1]\n\nInput: [EXAMPLE_INPUT_2]\nOutput: [EXAMPLE_OUTPUT_2]",
    why: "💡 Few-Shot Learning\n• Concrete examples beat lengthy instructions\n• Teaches exact pattern, tone, and format\n• Essential for niche or non-standard outputs",
  },
  {
    id: "verify",
    emoji: "✅",
    label: "Self-Verify",
    color: "#F97316",
    glow: "#F9731644",
    text: "Before responding:\n1. Verify each claim against context\n2. Flag uncertainty with [?]\n3. Check your reasoning is sound",
    why: "✅ Self-Consistency Check\n• Model reviews its output before finalising\n• Catches logical errors and unsupported claims\n• Built-in quality gate at zero extra cost",
  },
  {
    id: "tone",
    emoji: "🎨",
    label: "Tone & Style",
    color: "#6366F1",
    glow: "#6366F144",
    text: "Tone: [TONE]\nAudience: [AUDIENCE]\nAvoid: [AVOID_LIST]",
    why: "🎨 Audience Alignment\n• Steers vocabulary and register precisely\n• Forbidden words list prevents unwanted phrasing\n• Output lands right without manual post-editing",
  },
  {
    id: "grounding",
    emoji: "⚓",
    label: "Grounding",
    color: "#84CC16",
    glow: "#84CC1644",
    text: "Use ONLY the information provided below. Do not use outside knowledge.\nSource: [SOURCE_MATERIAL]",
    why: "⚓ Retrieval Grounding\n• Restricts model to your supplied sources only\n• Prevents hallucinated facts entirely\n• Makes responses auditable and compliance-safe",
  },
  {
    id: "uncertainty",
    emoji: "🤔",
    label: "Uncertainty",
    color: "#F43F5E",
    glow: "#F43F5E44",
    text: "If you are uncertain about any part of your answer, explicitly state your confidence level and say \"I don't know\" rather than guessing.",
    why: "🤔 Calibrated Confidence\n• Permits 'I don't know' — overrides confabulation\n• Surfaces real knowledge gaps honestly\n• Stops plausible-sounding but wrong answers",
  },
  {
    id: "separator",
    emoji: "─",
    label: "Separator",
    color: "#64748B",
    glow: "#64748B33",
    text: "\n---\n",
  },
];
